# -*- coding: utf-8 -*-
"""
Created on Wed Jul 13 00:21:21 2022

@author: Tomek
"""

'''
The sequence of triangle numbers is generated by adding the natural numbers. 
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. 
The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
'''
from datetime import datetime

raport = open('Problem 12.txt', mode = 'w+')
raport.write('{}: Zaczynamy zabawe!\n'.format(datetime.now()))

warunek = False
ilosc_dzielnikow=0
numer_liczby = 0
szukana_wartosc = 0

while warunek == False:
    
    if ilosc_dzielnikow>500:
        print('Znalazlem wartosc!')
        raport.write('{}: Znalazlem wartosc!\n'.format(datetime.now()))
        print('Szukana wartosc to: {}'.format(szukana_wartosc))
        raport.write('Szukana wartosc to: {}'.format(szukana_wartosc))
        raport.close()
        warunek = True
    else:
        numer_liczby += 1
        ilosc_dzielnikow = 1
        szukana_wartosc = 0
        
        for liczba1 in range(1,numer_liczby+1):
            szukana_wartosc+=liczba1
        
        print('Sprawdzam dla wartosci {}.'.format(szukana_wartosc))
        
        for liczba2 in range(1,int((szukana_wartosc)/2)+1):
            if szukana_wartosc%liczba2 == 0:
                ilosc_dzielnikow +=1
        print('Dla wartosci {} znalazlem {} dzielnikow'.format(szukana_wartosc,ilosc_dzielnikow))